---

- name: Install pre-req packages on nodes
  yum:
    name:
      - "wget"
      - "git"
      - "net-tools"
      - "bind-utils"
      - "iptables-services"
      - "bridge-utils"
      - "bash-completion"
      - "kexec-tools"
      - "sos"
      - "psacct"
      - "docker-1.12.6"
      - "ntp"
    state: "present"
  become: true

- name: Ensure NTP (for time synchronization) is running
  service: name=ntpd state=started enabled=yes
  become: true
  
- name: Create AWS directory
  file:
    path: /etc/aws
    state: directory
    mode: 0755
  become: true

- name: Copy AWS variable
  template:
    src: "../files/aws.conf"
    dest: "/etc/aws/aws.conf"
  become: true

- name: Configure docker storage
  template:
    src: "../files/docker-storage-setup"
    dest: "/etc/sysconfig/docker-storage-setup"
  become: true

- name: Setup docker storage
  command: /usr/bin/docker-storage-setup
  become: true

- name: Update docker options
  shell: "sed -i '/OPTIONS=.*/c\\OPTIONS=\"--selinux-enabled --insecure-registry 172.30.0.0/16\"' /etc/sysconfig/docker"
  become: true

- name: Enable docker on master and nodes
  systemd:
     name: docker
     enabled: yes
     state: started
  become: true
